name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    name: Ruff lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: [ '3.10.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt
      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1
        with:
          src: './finq'
          args: check --output-format=github --target-version=py310 --fix
        continue-on-error: false

  format:
    name: Black formatting
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: [ '3.10.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt
      - name: Format with Black
        uses: psf/black@stable
        with:
          src: './finq'

